/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf -t
Author: ГРАДИТЕЉСКО И СПОМЕНИЧКО НАСЛЕЂЕ (https://sketchfab.com/HeritagePhotogrammetry)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2610c661685042ca9c74de423013c4d9
Title: црква св Николе, Крупац
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
  }
  animations: any[]
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/3dobject/scene.gltf') as GLTFResult
  return (
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.material} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.material} />
        </group>
      </group>
  )
}

useGLTF.preload('assets/3dobject/scene.gltf')
