export const uliceRS: { label: string; value: string }[] = [
    { label: "Admirala Vukovića", value: "Admirala Vukovića" },
    { label: "Jovana Popovića", value: "Jovana Popovića" },
    { label: "Italijanskih Partizana", value: "Italijanskih Partizana" },
    { label: "Isidore Sekulić", value: "Isidore Sekulić" },
    { label: "Kirila Savića", value: "Kirila Savića" },
    { label: "Kumodraška", value: "Kumodraška" },
    { label: "Danijelova", value: "Danijelova" },
    { label: "Esad Pašina", value: "Esad Pašina" },
    { label: "Bože Jankovića", value: "Bože Jankovića" },
    { label: "Borisavljevićeva", value: "Borisavljevićeva" },
    { label: "Bukovička", value: "Bukovička" },
    { label: "Vitanovačka", value: "Vitanovačka" },
    { label: "Vojvode Đurovića", value: "Vojvode Đurovića" },
    { label: "Vojvode Skopljanca", value: "Vojvode Skopljanca" },
    { label: "Limska", value: "Limska" },
    { label: "Ljube Kovačevića", value: "Ljube Kovačevića" },
    { label: "Ljube Nedića", value: "Ljube Nedića" },
    { label: "Ljubićka", value: "Ljubićka" },
    { label: "Milana Bodanovića", value: "Milana Bodanovića" },
    { label: "Nestora Žučnog", value: "Nestora Žučnog" },
    { label: "Petra Gvojića", value: "Petra Gvojića" },
    { label: "Piroćančeva", value: "Piroćančeva" },
    { label: "Ribnička", value: "Ribnička" },
    { label: "Rucovićeva", value: "Rucovićeva" },
    { label: "Stevana Jakovljevića", value: "Stevana Jakovljevića" },
    { label: "Stevana Lilića", value: "Stevana Lilića" },
    { label: "Tolminska", value: "Tolminska" },
    { label: "Bajronova", value: "Bajronova" },
    { label: "Koste Jovanovića", value: "Koste Jovanovića" },
    { label: "Rađevska", value: "Rađevska" },
    { label: "Milovana Marinkovića", value: "Milovana Marinkovića" },
    { label: "Jove Ilića", value: "Jove Ilića" },
    { label: "Prilučka", value: "Prilučka" },
    { label: "Dimitrija Stamenkovića", value: "Dimitrija Stamenkovića" },
    { label: "Lepenička", value: "Lepenička" },
    { label: "Pukovnika Purića", value: "Pukovnika Purića" },
    { label: "Bulevar Oslobođenja", value: "Bulevar Oslobođenja" },
    { label: "Generala Anrija", value: "Generala Anrija" },
    { label: "Gostivarska", value: "Gostivarska" },
    { label: "Dukljaninova", value: "Dukljaninova" },
    { label: "Jošanička", value: "Jošanička" },
    { label: "Vojvode Stepe", value: "Vojvode Stepe" },
    { label: "Milana Raspoopvića", value: "Milana Raspoopvića" },
    { label: "Nikšićka", value: "Nikšićka" },
    { label: "Milke Grgurove", value: "Milke Grgurove" },
    { label: "Ljube Šercera", value: "Ljube Šercera" },
    { label: "Nikole Miljanovića", value: "Nikole Miljanovića" },
    { label: "Kostolačka", value: "Kostolačka" },
    { label: "Ljube Vučkovića", value: "Ljube Vučkovića" },
    { label: "Vorornješka", value: "Vorornješka" },
    { label: "Gruzijska", value: "Gruzijska" },
    { label: "Danila Bojovića", value: "Danila Bojovića" },
    { label: "Darvinova", value: "Darvinova" },
    { label: "Zlarinska", value: "Zlarinska" },
    { label: "Kalnička", value: "Kalnička" },
    { label: "Unska", value: "Unska" },
    { label: "Sanska", value: "Sanska" },
    { label: "Podravska", value: "Podravska" },
    { label: "Bjelovarska", value: "Bjelovarska" },
    { label: "Gligorija Vozarevića", value: "Gligorija Vozarevića" },
    { label: "Kačarska", value: "Kačarska" },
    { label: "Kralja Vladimira", value: "Kralja Vladimira" },
    { label: "Milana Šaranovića", value: "Milana Šaranovića" },
    { label: "Nikole Đurkovića", value: "Nikole Đurkovića" },
    { label: "Petrovačka", value: "Petrovačka" },
    { label: "Sićevačka", value: "Sićevačka" },
    { label: "Svetislava Cvijanovića", value: "Svetislava Cvijanovića" }
];

export const uliceRSCyr: { label: string; value: string }[] = [
    { label: "Адмирала Вуковића", value: "Адмирала Вуковића" },
    { label: "Италијанских Партизана", value: "Италијанских Партизана" },
    { label: "Јована Поповића", value: "Јована Поповића" },
    { label: "Исидоре Секулић", value: "Исидоре Секулић" },
    { label: "Кирила Савића", value: "Кирила Савића" },
    { label: "Кумодрашка", value: "Кумодрашка" },
    { label: "Данијелова", value: "Данијелова" },
    { label: "Есад Пашина", value: "Есад Пашина" },
    { label: "Боже Јанковића", value: "Боже Јанковића" },
    { label: "Борисављевићева", value: "Борисављевићева" },
    { label: "Буковичка", value: "Буковичка" },
    { label: "Витановачка", value: "Витановачка" },
    { label: "Војводе Ђуровића", value: "Војводе Ђуровића" },
    { label: "Војводе Скопљанца", value: "Војводе Скопљанца" },
    { label: "Лимска", value: "Лимска" },
    { label: "Љубе Ковачевића", value: "Љубе Ковачевића" },
    { label: "Љубе Недића", value: "Љубе Недића" },
    { label: "Љубићка", value: "Љубићка" },
    { label: "Милана Богдановића", value: "Милана Богдановића" },
    { label: "Нестора Жучног", value: "Нестора Жучног" },
    { label: "Петра Гвојића", value: "Петра Гвојића" },
    { label: "Пироћанчева", value: "Пироћанчева" },
    { label: "Рибничка", value: "Рибничка" },
    { label: "Руцовићева", value: "Руцовићева" },
    { label: "Стевана Јаковљевића", value: "Стевана Јаковљевића" },
    { label: "Стевана Лилића", value: "Стевана Лилића" },
    { label: "Толминска", value: "Толминска" },
    { label: "Бајронова", value: "Бајронова" },
    { label: "Косте Јовановића", value: "Косте Јовановића" },
    { label: "Рађевска", value: "Рађевска" },
    { label: "Милована Маринковића", value: "Милована Маринковића" },
    { label: "Јове Илића", value: "Јове Илића" },
    { label: "Прилучка", value: "Прилучка" },
    { label: "Димитрија Стаменковића", value: "Димитрија Стаменковића" },
    { label: "Лепеничка", value: "Лепеничка" },
    { label: "Пуковинка Пурића", value: "Пуковинка Пурића" },
    { label: "Булевар Ослобођења", value: "Булевар Ослобођења" },
    { label: "Војводе Степе", value: "Војводе Степе" },
    { label: "Генерала Анрија", value: "Генерала Анрија" },
    { label: "Гостиварска", value: "Гостиварска" },
    { label: "Дукљанинова", value: "Дукљанинова" },
    { label: "Јошаничка", value: "Јошаничка" },
    { label: "Милана Распоповића", value: "Милана Распоповића" },
    { label: "Никшићка", value: "Никшићка" },
    { label: "Милке Гргурове", value: "Милке Гргурове" },
    { label: "Љубе Шерцера", value: "Љубе Шерцера" },
    { label: "Николе Миљановића", value: "Николе Миљановића" },
    { label: "Костолачка", value: "Костолачка" },
    { label: "Љубе Вучковића", value: "Љубе Вучковића" },
    { label: "Вороњешка", value: "Вороњешка" },
    { label: "Грузијска", value: "Грузијска" },
    { label: "Данила Бојовића", value: "Данила Бојовића" },
    { label: "Дарвинова", value: "Дарвинова" },
    { label: "Зларинска", value: "Зларинска" },
    { label: "Калничка", value: "Калничка" },
    { label: "Унска", value: "Унска" },
    { label: "Санска", value: "Санска" },
    { label: "Подравска", value: "Подравска" },
    { label: "Бјеловарска", value: "Бјеловарска" },
    { label: "Глигорија Возаревића", value: "Глигорија Возаревића" },
    { label: "Качарска", value: "Качарска" },
    { label: "Краља Владимира", value: "Краља Владимира" },
    { label: "Милована Шарановића", value: "Милована Шарановића" },
    { label: "Николе Ђурковића", value: "Николе Ђурковића" },
    { label: "Петровачка", value: "Петровачка" },
    { label: "Сићевачка", value: "Сићевачка" },
    { label: "Светислава Цвијановића", value: "Светислава Цвијановића" }
];